### PR TITLE
Api

### PR DESCRIPTION
**Pull request by ropergroup**
Created API Controller, routes.

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
Nice clean pull request but you are missing tests for the app/controllers/api/events_controller.rb, @roperxyz

**Comment by ropergroup** [comment]
Tests are added.

**Comment by ropergroup** [comment]
Don't merge this pull request until I have finished the javascript.

**Comment by brittanyjspringer** [comment]
@roperxyz there are not any commits for Blocmetrics for Checkpoint #7. The JS snippet will go to Blocitoff. Going to merge now!

**Pull request merged**
